"""
Author: Reynaldo Gomez
Last Edited: 3/25/2026

Description — Pseudo-Label Run v2: SE attention only, targeted pseudo-labeling.

Extends yield_se_only.py with a larger training set assembled from two sources:

    1. Original labeled data  — ~138k samples from LSWMD.pkl (ground truth)
    2. Pseudo-labeled data     — defect-class-only samples from data/pseudo_labeled.pkl,
       generated by yield_pseudolabel.py using the best_se_only.pt checkpoint.
       Acceptance thresholds: 0.95 default, 0.999 for Donut, 0.98 for Near-full.
       Per-class cap: 3× the original labeled count for that class.

v1 failure: including none pseudo-labels (248,215 samples) pushed the combined
dataset to 87% none. The 3× cap (353,835) was never triggered since 248,215 < cap,
so all none pseudo-labels passed through uncapped. WeightedRandomSampler could not
overcome this density and the model collapsed to predicting none for everything.

v2 fix (Option B): pseudo-labeling is restricted to the 5 classes that actually
need more data based on se-only-v1 F1 scores:
    Targeted (F1 < 0.85 or very low sample count):
        Loc (0.77), Edge-Loc (0.81), Donut (~0.55), Near-full (~0.60)
    Excluded (high F1 or source-model uncertainty makes pseudo-labels unreliable):
        none (0.99), Edge-Ring (>0.90), Center (>0.90), Random (>0.90), Scratch (0.80)

Combined dataset: ~185k samples split 80/20 → ~148k train / ~37k val.
The validation set is dominated by ground-truth original labeled data.

Model, loss, optimizer, and augmentation are identical to yield_se_only.py
so that dataset composition is the only variable that changes.

Usage:
    python pseudo_se_only.py
    - trains for 40 epochs, saves best checkpoint when val loss improves
    - prints per-class classification report at the end
    - appends one row to ../results.csv
"""

import sys
import time
import types
import pickle as pkl
from pathlib import Path

import numpy as np
import pandas
import pandas.core.indexes.base
import pandas.core.indexes.range
import pandas.core.indexes.multi

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from skimage.transform import resize

# tracker.py lives one level up (Yield CNN/)
sys.path.insert(0, str(Path(__file__).parent.parent))
from tracker import log_run

# --------------------------------------------------------------------------- #
# pandas 2.x compat patch
# LSWMD.pkl was saved with Python 2 + pandas ~0.19. Inject fake modules so
# pickle's import machinery can find the old paths.
# --------------------------------------------------------------------------- #
_pi         = types.ModuleType("pandas.indexes")
_pi.base    = pandas.core.indexes.base
_pi.range   = pandas.core.indexes.range
_pi.multi   = pandas.core.indexes.multi
_pi.numeric = pandas.core.indexes.base

sys.modules["pandas.indexes"]         = _pi
sys.modules["pandas.indexes.base"]    = pandas.core.indexes.base
sys.modules["pandas.indexes.range"]   = pandas.core.indexes.range
sys.modules["pandas.indexes.multi"]   = pandas.core.indexes.multi
sys.modules["pandas.indexes.numeric"] = pandas.core.indexes.base
# --------------------------------------------------------------------------- #

DEVICE     = "cuda" if torch.cuda.is_available() else "cpu"
IMG_SIZE   = 64
BATCH_SIZE = 128
EPOCHS     = 40
LR         = 3e-4

PKL_PATH        = Path(__file__).parent.parent / "Dataset" / "LSWMD.pkl"
PSEUDO_PATH     = Path(__file__).parent.parent / "data"    / "pseudo_labeled.pkl"
CHECKPOINT_PATH = Path(__file__).parent.parent / "checkpoints" / "best_se_pseudo_v2.pt"

# Per-class cap applied to pseudo-labels at load time.
# yield_pseudolabel.py did not apply apply_class_caps correctly — Donut (134×),
# Near-full (6.6×), and Random (7.1×) all exceed the intended 3× limit.
# Cap is enforced here via random sampling (seed 42) before concatenation.
ORIG_LABELED_COUNTS = {
    "none": 117945, "Edge-Ring": 7744, "Center": 3435, "Edge-Loc": 4151,
    "Loc": 2874, "Scratch": 954, "Random": 693, "Donut": 555, "Near-full": 119,
}
MAX_PSEUDO_MULTIPLIER = 3

# Classes excluded from pseudo-labeling. These already have F1 > 0.90 in
# se-only-v1 and adding pseudo-labels provides no benefit while inflating the
# dataset. none in particular had 248,215 pseudo-samples — all passing the 3×
# cap (353,835 > 248,215) — which made the combined dataset 87% none and caused
# the model to collapse to the majority-class predictor in v1.
PSEUDO_EXCLUDED_CLASSES = {"none", "Edge-Ring", "Center", "Random", "Scratch"}


# --------------------------------------------------------------------------- #
# 1. DATA
# --------------------------------------------------------------------------- #

def _unwrap_label(val):
    """
    LSWMD stores labels as nested arrays: [['Edge-Loc']] or [[]] for unlabeled.
    Peels nesting until it reaches the scalar string.
    Returns None for empty arrays so they can be filtered out.
    """
    while isinstance(val, (list, np.ndarray)):
        if len(val) == 0:
            return None
        val = val[0]
    return str(val).strip()


def load_pkl(pkl_path: Path):
    with pkl_path.open("rb") as f:
        df = pkl.load(f, encoding="latin-1")

    raw_labels = df["failureType"].apply(_unwrap_label)
    mask       = raw_labels.notna()
    df         = df[mask].reset_index(drop=True)
    raw_labels = raw_labels[mask].reset_index(drop=True)

    maps = []
    for wm in df["waferMap"]:
        arr = np.array(wm, dtype=np.float32)
        arr = resize(arr, (IMG_SIZE, IMG_SIZE),
                     anti_aliasing=False, preserve_range=True)
        maps.append(arr)

    X = np.stack(maps)
    y = raw_labels.values

    print(f"Loaded {len(X):,} labeled wafers across {len(set(y))} classes")
    print(pandas.Series(y).value_counts().to_string())
    return X, y


def encode_labels(y_raw):
    """
    Converts string class names to integers 0..K-1.
    Sorted alphabetically so the mapping is reproducible across runs.
    """
    classes    = sorted(set(y_raw))
    cls_to_idx = {c: i for i, c in enumerate(classes)}
    y_idx      = np.array([cls_to_idx[v] for v in y_raw], dtype=np.int64)
    return y_idx, classes


def load_pseudo(pseudo_path: Path, classes: list):
    """
    Loads pseudo_labeled.pkl and returns (X, y_idx) aligned to the class list
    established by the original labeled data.

    Only returns pseudo-labels for classes NOT in PSEUDO_EXCLUDED_CLASSES.
    Excluded classes already have high F1 in se-only-v1; adding pseudo-labels
    for them inflates the dataset without improving the weak classes.

    Verifies that the checkpoint's class list matches so integer labels are
    consistent across both sources before concatenation.
    """
    with pseudo_path.open("rb") as f:
        data = pkl.load(f)

    pseudo_classes = list(data["classes"])
    assert pseudo_classes == classes, (
        f"Class mismatch between pseudo-labeled checkpoint and original labels.\n"
        f"  Original: {classes}\n"
        f"  Pseudo:   {pseudo_classes}"
    )

    X = data["X"]
    y = data["y"].astype(np.int64)

    print(f"Loaded {len(X):,} raw pseudo-labeled samples (pre-cap, pre-exclusion)")

    # Apply per-class cap and exclude high-F1 classes.
    # The saved pkl has Donut at 134× the original count due to a missing cap
    # in yield_pseudolabel.py. Random sampling with a fixed seed is used because
    # confidence scores were not saved in the pkl.
    rng = np.random.default_rng(42)
    keep = []
    for i, cls in enumerate(classes):
        if cls in PSEUDO_EXCLUDED_CLASSES:
            print(f"  Skipping {cls} pseudo-labels (excluded — already high F1)")
            continue
        cls_idx = np.where(y == i)[0]
        cap     = ORIG_LABELED_COUNTS.get(cls, 0) * MAX_PSEUDO_MULTIPLIER
        if len(cls_idx) > cap:
            cls_idx = rng.choice(cls_idx, size=cap, replace=False)
        keep.append(cls_idx)

    keep = np.concatenate(keep) if keep else np.array([], dtype=np.int64)
    X = X[keep]
    y = y[keep]

    print(f"After exclusion + {MAX_PSEUDO_MULTIPLIER}× cap: {len(X):,} pseudo-labeled samples")
    print(pandas.Series([classes[i] for i in y]).value_counts().to_string())
    return X, y


class WaferDataset(Dataset):
    """
    PyTorch Dataset for LSWMD wafer maps.
    Augmentation (rot90 + hflip) is applied only during training.
    Defect patterns are rotationally symmetric so these are valid transforms.
    No CoordConv — wafer map is passed as a single channel (ablation Run B).
    """
    def __init__(self, X: np.ndarray, y: np.ndarray, augment: bool = False):
        self.X       = X
        self.y       = y
        self.augment = augment

    def __len__(self):
        return len(self.X)

    def _augment(self, x: torch.Tensor) -> torch.Tensor:
        k = torch.randint(0, 4, (1,)).item()
        x = torch.rot90(x, k, dims=(1, 2))
        if torch.rand(1).item() < 0.5:
            x = torch.flip(x, dims=(2,))
        return x

    def __getitem__(self, idx):
        x = torch.tensor(self.X[idx], dtype=torch.float32).unsqueeze(0)
        if x.max() > 1.5:
            x = x / 255.0
        if self.augment:
            x = self._augment(x)
        return x, int(self.y[idx])


# --------------------------------------------------------------------------- #
# 2. MODEL
# --------------------------------------------------------------------------- #

class SEBlock(nn.Module):
    """
    Squeeze-and-Excitation block (Hu et al., 2018).

    Globally pools the feature map (squeeze), passes through a small FC
    bottleneck (excitation), then scales each channel by its learned attention
    weight. This lets the network suppress uninformative channels and amplify
    useful ones without adding many parameters.

    reduction=16 is the standard bottleneck ratio from the original paper.
    """
    def __init__(self, channels: int, reduction: int = 16):
        super().__init__()
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.fc   = nn.Sequential(
            nn.Linear(channels, max(channels // reduction, 1), bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(max(channels // reduction, 1), channels, bias=False),
            nn.Sigmoid(),
        )

    def forward(self, x):
        b, c, _, _ = x.shape
        w = self.pool(x).view(b, c)
        w = self.fc(w).view(b, c, 1, 1)
        return x * w


class ResidualBlock(nn.Module):
    """
    Two conv layers with a skip connection and SE channel attention.

    The skip adds the block's input directly to its output before the final
    activation: out = act(SE(F(x)) + x). SE attention is applied after the
    conv path and before the residual add.

    stride=2 handles spatial downsampling (replaces MaxPool from the baseline).
    When stride != 1 or channels change, the skip uses a 1x1 conv to match dims.
    """
    def __init__(self, in_ch: int, out_ch: int, stride: int = 1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_ch, out_ch, 3, stride=stride, padding=1, bias=False)
        self.bn1   = nn.BatchNorm2d(out_ch)
        self.conv2 = nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False)
        self.bn2   = nn.BatchNorm2d(out_ch)
        self.act   = nn.SiLU(inplace=True)

        self.se = SEBlock(out_ch)

        self.skip = nn.Identity()
        if stride != 1 or in_ch != out_ch:
            self.skip = nn.Sequential(
                nn.Conv2d(in_ch, out_ch, 1, stride=stride, bias=False),
                nn.BatchNorm2d(out_ch),
            )

    def forward(self, x):
        identity = self.skip(x)
        out = self.act(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out = self.se(out)                       # channel attention after conv path
        return self.act(out + identity)


class WaferResNet(nn.Module):
    """
    WaferResNet with SE attention in every block, no CoordConv.

    Channel progression: 32→64→128→256. Each stage uses stride=2 for
    downsampling. First block takes in_ch=1 (raw wafer map only).

    Input:  (N, 1, 64, 64)
    Output: (N, K) logits
    """
    def __init__(self, num_classes: int):
        super().__init__()
        self.features = nn.Sequential(
            ResidualBlock(1,   32,  stride=2),   # → (32, 32, 32)
            ResidualBlock(32,  64,  stride=2),   # → (64, 16, 16)
            ResidualBlock(64,  128, stride=2),   # → (128, 8, 8)
            ResidualBlock(128, 256, stride=2),   # → (256, 4, 4)
            nn.AdaptiveAvgPool2d((1, 1)),         # → (256, 1, 1)
        )
        self.dropout    = nn.Dropout(0.4)
        self.classifier = nn.Linear(256, num_classes)

    def forward(self, x):
        x = self.features(x)
        x = x.flatten(1)
        x = self.dropout(x)
        return self.classifier(x)


# --------------------------------------------------------------------------- #
# 3. LOSS
# --------------------------------------------------------------------------- #

class FocalLoss(nn.Module):
    """
    Focal Loss (Lin et al., 2017).

    focal_weight = (1 - pt)^gamma
        pt    = probability assigned to the correct class
        gamma = 2.0 (standard starting point)

    When pt ≈ 1.0 (easy correct prediction): weight ≈ 0 → near-zero contribution
    When pt ≈ 0.0 (hard wrong prediction):   weight ≈ 1 → full cross-entropy

    The ~29k "none" wafers the model already predicts correctly contribute almost
    nothing. The optimizer spends its capacity on Donut, Scratch, and other
    hard classes instead.
    """
    def __init__(self, gamma: float = 2.0):
        super().__init__()
        self.gamma = gamma

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        ce           = F.cross_entropy(logits, targets, reduction="none")
        pt           = torch.exp(-ce)
        focal_weight = (1 - pt) ** self.gamma
        return (focal_weight * ce).mean()


# --------------------------------------------------------------------------- #
# 4. TRAINING & EVALUATION
# --------------------------------------------------------------------------- #

def train_one_epoch(model, loader, optimizer, loss_fn):
    model.train()
    total_loss, correct, total = 0.0, 0, 0

    for x, y in loader:
        x = x.to(DEVICE)
        y = torch.as_tensor(y, dtype=torch.long, device=DEVICE)

        optimizer.zero_grad(set_to_none=True)
        logits = model(x)
        loss   = loss_fn(logits, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * x.size(0)
        correct    += (logits.argmax(dim=1) == y).sum().item()
        total      += x.size(0)

    return total_loss / total, correct / total


@torch.no_grad()
def eval_one_epoch(model, loader, loss_fn):
    """
    @torch.no_grad() disables gradient tracking — faster and uses less memory.
    model.eval() disables dropout and uses running stats for batchnorm.
    """
    model.eval()
    total_loss, correct, total = 0.0, 0, 0

    for x, y in loader:
        x = x.to(DEVICE)
        y = torch.as_tensor(y, dtype=torch.long, device=DEVICE)

        logits = model(x)
        loss   = loss_fn(logits, y)

        total_loss += loss.item() * x.size(0)
        correct    += (logits.argmax(dim=1) == y).sum().item()
        total      += x.size(0)

    return total_loss / total, correct / total


@torch.no_grad()
def collect_predictions(model, loader):
    """Run inference over the full val set, return (y_pred, y_true) arrays."""
    model.eval()
    all_preds, all_targets = [], []

    for x, y in loader:
        logits = model(x.to(DEVICE))
        all_preds.append(logits.argmax(dim=1).cpu().numpy())
        all_targets.append(np.asarray(y))

    return np.concatenate(all_preds), np.concatenate(all_targets)


# --------------------------------------------------------------------------- #
# 5. MAIN
# --------------------------------------------------------------------------- #

def main():
    t_start = time.time()

    # Original labeled data (ground truth anchor)
    print("Loading original labeled dataset...")
    X_orig, y_raw  = load_pkl(PKL_PATH)
    y_orig, classes = encode_labels(y_raw)
    K               = len(classes)
    print(f"\nClasses ({K}):", classes)

    # Pseudo-labeled data
    print("\nLoading pseudo-labeled dataset...")
    X_pseudo, y_pseudo = load_pseudo(PSEUDO_PATH, classes)

    # Combine
    X_raw = np.concatenate([X_orig, X_pseudo], axis=0)
    y_idx = np.concatenate([y_orig, y_pseudo], axis=0)

    print(f"\nCombined: {len(X_raw):,} total  "
          f"({len(X_orig):,} ground truth + {len(X_pseudo):,} pseudo-labeled)")
    print("\nFull class distribution:")
    print(pandas.Series([classes[i] for i in y_idx]).value_counts().to_string())

    X_tr, X_va, y_tr, y_va = train_test_split(
        X_raw, y_idx, test_size=0.2, random_state=42, stratify=y_idx
    )

    train_ds = WaferDataset(X_tr, y_tr, augment=True)
    val_ds   = WaferDataset(X_va, y_va, augment=False)

    # WeightedRandomSampler: rare classes get sampled more often so every
    # training batch sees a roughly balanced class distribution
    class_counts   = np.bincount(y_tr, minlength=K)
    class_weights  = 1.0 / np.maximum(class_counts, 1)
    sample_weights = class_weights[y_tr]
    sampler = WeightedRandomSampler(sample_weights, len(sample_weights), replacement=True)

    # num_workers=0 on Windows: multiprocessing workers require pickling the full
    # dataset through a named pipe whose buffer is ~64 KB — far smaller than
    # 138 K wafer maps — causing OSError [Errno 22] / truncated-pickle crashes.
    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, sampler=sampler,
                              num_workers=0, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=256, shuffle=False,
                              num_workers=0, pin_memory=True)

    model     = WaferResNet(num_classes=K).to(DEVICE)
    loss_fn   = FocalLoss(gamma=2.0)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=3
    )

    print(f"\nTraining on {DEVICE}")
    print(f"Train: {len(train_ds):,} | Val: {len(val_ds):,}\n")

    best_val_loss = float("inf")
    best_epoch    = 1

    for epoch in range(1, EPOCHS + 1):
        tr_loss, tr_acc = train_one_epoch(model, train_loader, optimizer, loss_fn)
        va_loss, va_acc = eval_one_epoch(model, val_loader,   loss_fn)
        scheduler.step(va_loss)

        print(f"Epoch {epoch:02d} | "
              f"train loss {tr_loss:.4f} acc {tr_acc:.4f} | "
              f"val loss {va_loss:.4f} acc {va_acc:.4f}")

        if va_loss < best_val_loss:
            best_val_loss = va_loss
            best_epoch    = epoch
            torch.save(
                {"model": model.state_dict(), "classes": classes},
                CHECKPOINT_PATH,
            )
            print(f"  Saved best model (val loss {va_loss:.4f})")

    train_time = time.time() - t_start
    print(f"\nTraining complete. Best val loss: {best_val_loss:.4f}  (epoch {best_epoch})")

    # Per-class metrics
    y_pred, y_true = collect_predictions(model, val_loader)
    report         = classification_report(y_true, y_pred, target_names=classes, output_dict=True)
    per_class_f1   = {cls: report[cls]["f1-score"] for cls in classes}
    macro_f1       = report["macro avg"]["f1-score"]
    val_acc        = float((y_pred == y_true).mean())

    print("\n" + classification_report(y_true, y_pred, target_names=classes))

    log_run(
        exp_id       = "se-pseudo-v2",
        model        = "WaferResNet",
        loss_fn      = "FocalLoss(gamma=2)",
        epochs       = EPOCHS,
        lr           = LR,
        batch_size   = BATCH_SIZE,
        augmentation = "rot90+hflip",
        val_accuracy = val_acc,
        val_loss     = best_val_loss,
        macro_f1     = macro_f1,
        per_class_f1 = per_class_f1,
        best_epoch   = best_epoch,
        train_time_s = train_time,
        checkpoint   = CHECKPOINT_PATH.relative_to(Path(__file__).parent.parent).as_posix(),
        notes        = (
            "SE-only + targeted pseudo-labeling (v2). "
            "Excluded none/Edge-Ring/Center/Random pseudo-labels — these classes already "
            "have F1 > 0.90 in se-only-v1 and adding pseudo-labels inflated the dataset "
            "to 87% none in v1, collapsing the model to majority-class prediction. "
            "Pseudo-labels kept only for: Loc, Edge-Loc, Donut, Near-full "
            "(the weak classes). Scratch excluded — source model was uncertain on Scratch "
            "and pseudo-labels are unreliable. Combined ~185k samples, val is predominantly ground truth."
        ),
    )


if __name__ == "__main__":
    main()
