"""
Author: Reynaldo Gomez

EXP-12 — Synthetic Defect Generation

Plan:
    Generate wafer maps with known defect patterns using numpy geometry.
    Target: 2000+ synthetic samples for Donut and Near-full specifically,
    as these are the two most underrepresented classes in LSWMD.

    Patterns to generate:
        Donut     — concentric ring with gap (annulus mask)
        Near-full — near-complete fill with small clear region
        Edge-Ring — solid ring at wafer edge
        Scratch   — thin diagonal line across wafer
        Center    — small cluster at center coordinates
        Loc       — cluster at random off-center location

    Pipeline:
        1. Generate N synthetic maps per target class using numpy
        2. Save as numpy arrays with string labels
        3. Merge with real LSWMD labeled data before train/val split
        4. Retrain and compare macro F1 vs baseline

Expected outcome:
    - Donut F1 0.56 → 0.75+ after adding 1000+ synthetic Donut maps
    - Near-full recall improvement

Depends on: tracker.py
"""

# TODO: implement before EXP-11 (pseudo-labeling) so pseudo-labels
#       are generated by a model already exposed to synthetic Donut/Near-full
